import * as vscode from 'vscode';
import { getBestSuggestions } from '../core/algorithm';
import { isCodeSpellEnabled } from '../core/config';

export class SpellCodeActionProvider implements vscode.CodeActionProvider {
  provideCodeActions(
    document: vscode.TextDocument,
    range: vscode.Range | vscode.Selection,
    context: vscode.CodeActionContext,
    token: vscode.CancellationToken,
  ): vscode.ProviderResult<(vscode.Command | vscode.CodeAction)[]> {
    if (!isCodeSpellEnabled()) {
      return [];
    }

    /* =========================================================
     * 🔍 FIND DIAGNOSTICS
     * Find any diagnostic generated by our provider
     * ========================================================= */
    const codeSpellDiagnostics = context.diagnostics.filter(
      (d) => d.source === 'ATM code-spell',
    );

    if (codeSpellDiagnostics.length === 0) {
      return [];
    }

    // Only target the diagnostics that actually overlap with the user's cursor/selection
    // to prevent showing suggestions for 2+ errors on the same line at once
    let targetDiagnostics = codeSpellDiagnostics.filter(
      (d) => d.range.intersection(range) || d.range.contains(range.start)
    );

    // Filter down to a single diagnostic to keep Quick Fix menu super clean
    const diagToFix = targetDiagnostics.length > 0 ? targetDiagnostics[0] : codeSpellDiagnostics[0];

    const actions: vscode.CodeAction[] = [];
    const wordRange = diagToFix.range;
    const word = document.getText(wordRange);

    /* =========================================================
     * 💡 GENERATE SUGGESTIONS
     * Generate 1 single BEST suggestion
     * ========================================================= */
    const suggestions = getBestSuggestions(word, 1);

    for (const sugg of suggestions) {
      /* =========================================================
       * 🔄 SUGGESTION ACTION
       * Generate action: Change to "suggestion"
       * ========================================================= */
      const action = new vscode.CodeAction(
        `✨ Fix: "${sugg}"`,
        vscode.CodeActionKind.QuickFix,
      );
      action.edit = new vscode.WorkspaceEdit();
      action.edit.replace(document.uri, wordRange, sugg);
      action.diagnostics = [diagToFix];
      action.isPreferred = true; // Allows fixing it quickly with Shift+Alt+.
      actions.push(action);
    }

    /* =========================================================
     * 🏢 WORKSPACE SETTINGS ACTION (middle)
     * Saves into .vscode/settings.json of the current workspace
     * ========================================================= */
    const workspaceAction = new vscode.CodeAction(
      `📁 Add "${word}" to Workspace (.vscode/settings.json)`,
      vscode.CodeActionKind.QuickFix,
    );
    workspaceAction.command = {
      command: 'atm.code-spell.addWordWorkspace',
      title: 'Add Word Workspace',
      arguments: [word],
    };

    /* =========================================================
     * 👤 USER SETTINGS ACTION (last)
     * Saves into the global user settings.json
     * ========================================================= */
    const userAction = new vscode.CodeAction(
      `👤 Add "${word}" to User Settings (settings.json)`,
      vscode.CodeActionKind.QuickFix,
    );
    userAction.command = {
      command: 'atm.code-spell.addWordUser',
      title: 'Add Word User',
      arguments: [word],
    };

    actions.push(workspaceAction, userAction);

    return actions;
  }
}
