import * as vscode from 'vscode';
import { getSuggestions } from '../core/suggestions';

export class SpellCodeActionProvider implements vscode.CodeActionProvider {
  provideCodeActions(
    document: vscode.TextDocument,
    range: vscode.Range | vscode.Selection,
    context: vscode.CodeActionContext,
    token: vscode.CancellationToken,
  ): vscode.ProviderResult<(vscode.Command | vscode.CodeAction)[]> {
    // Find any diagnostic generated by our provider
    const diagnostics = context.diagnostics.filter(
      (d) => d.source === 'ATM code-spell',
    );
    const actions: vscode.CodeAction[] = [];

    for (const diag of diagnostics) {
      const wordRange = diag.range;
      const word = document.getText(wordRange);

      // Generate up to 3 suggestions max
      const suggestions = getSuggestions(word, 3);

      for (const sugg of suggestions) {
        // Generate action: Change to "suggestion"
        const action = new vscode.CodeAction(
          `Replace with "${sugg}"`,
          vscode.CodeActionKind.QuickFix,
        );
        action.edit = new vscode.WorkspaceEdit();
        action.edit.replace(document.uri, wordRange, sugg);
        action.diagnostics = [diag];
        action.isPreferred = true; // Allows fixing it quickly with Shift+Alt+.
        actions.push(action);
      }

      // Action: Add to User Settings (Shorter text first)
      const userAction = new vscode.CodeAction(
        `Add "${word}" to User Settings`,
        vscode.CodeActionKind.QuickFix,
      );
      userAction.command = {
        command: 'atm.code-spell.addWordUser',
        title: 'Add Word User',
        arguments: [word],
      };

      // Action: Add to Workspace Settings (Longer text at the end)
      const workspaceAction = new vscode.CodeAction(
        `Add "${word}" to Workspace Settings`,
        vscode.CodeActionKind.QuickFix,
      );
      workspaceAction.command = {
        command: 'atm.code-spell.addWordWorkspace',
        title: 'Add Word Workspace',
        arguments: [word],
      };

      actions.push(userAction, workspaceAction);
    }

    return actions;
  }
}
