import * as vscode from 'vscode';
import { getSuggestions } from '../core/suggestions';

export class SpellCodeActionProvider implements vscode.CodeActionProvider {
  provideCodeActions(
    document: vscode.TextDocument,
    range: vscode.Range | vscode.Selection,
    context: vscode.CodeActionContext,
    token: vscode.CancellationToken,
  ): vscode.ProviderResult<(vscode.Command | vscode.CodeAction)[]> {
    // Find any diagnostic generated by our provider
    const diagnostics = context.diagnostics.filter(
      (d) => d.source === 'ATM code-spell',
    );
    const actions: vscode.CodeAction[] = [];

    for (const diag of diagnostics) {
      const wordRange = diag.range;
      const word = document.getText(wordRange);

      // Generate up to 5 suggestions max
      const suggestions = getSuggestions(word, 5);

      for (const sugg of suggestions) {
        // Generate action: Change to "suggestion"
        const action = new vscode.CodeAction(
          `Sustituir con "${sugg}"`,
          vscode.CodeActionKind.QuickFix,
        );
        action.edit = new vscode.WorkspaceEdit();
        action.edit.replace(document.uri, wordRange, sugg);
        action.diagnostics = [diag];
        action.isPreferred = true; // Allows fixing it quickly with Shift+Alt+.
        actions.push(action);
      }

      // Action: Add to Document/Dictionary
      const ignoreAction = new vscode.CodeAction(
        `Agregar "${word}" al Diccionario ATM`,
        vscode.CodeActionKind.QuickFix,
      );
      ignoreAction.command = {
        command: 'atm.code-spell.addWord',
        title: 'Add Word',
        arguments: [word],
      };
      actions.push(ignoreAction);
    }

    return actions;
  }
}
